"""Populate TFI International consolidated historicals (FY20-FY25) into the
template generated by the financial_model builder.

TFI International files as a Canadian foreign private issuer (Form 40-F,
CIK 0001588823) under IFRS. The standardized ifrs-full tags exposed by
EDGAR's Company Facts API cover the consolidated income statement,
cash flow statement, and balance sheet. Per-segment revenue / EBIT are
NOT in the standard taxonomy and are not populated here -- the segment
P&L block in the template is left blank for the modeler to fill in from
Note 25 (Segmented Information) of the 40-F.

Known data quirks the populator preserves as-tagged:
  - FY24 CashAndCashEquivalents is tagged as 0 in both the original and
    the FY25 40-F restated comparative. The actual year-end balance has
    to be entered manually from the BS in the 40-F PDF.
  - FY21 / FY22 FinanceCosts are tagged with a negative sign in TFI's
    XBRL (an inconsistency between filings). The populator takes abs()
    so "Interest expense" remains positive.
  - Standalone Goodwill is only tagged through FY22. FY23+ rolls into
    IntangibleAssetsAndGoodwill -- that combined value lands in the
    template's "Intangible assets, net" row.
"""

from __future__ import annotations

import json
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

TFI_CIK = "0001588823"
FACTS_URL = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{TFI_CIK}.json"
USER_AGENT = "industrials-optima/0.1 (payton.liske@gmail.com)"

# Per the Moog template layout: FY10 sits at column G (index 7), each
# subsequent year occupies five columns (Q1..Q4 + FY total). The FY total
# column for fiscal year N is therefore at index 7 + 5*(N - 10).
def fy_total_col(fy: int) -> int:
    return 7 + 5 * (fy - 10)


# A single mapping entry from a template row to one (or more) ifrs-full tags.
@dataclass
class Mapping:
    row: int
    tags: tuple[str, ...]    # try each tag in order; first hit wins
    kind: str                 # "duration" (period-flow) or "instant" (point-in-time)
    scale: float = 1_000_000  # divide raw USD by this; use 1 for per-share, 1000 for share counts
    sign: int = 1             # multiply by this (use -1 to negate)
    abs_value: bool = False   # take abs() before scaling (for tags with inconsistent sign)


# ---------------------------------------------------------------------------
# Mapping: ifrs-full tag -> Moog template row.
#
# Where the IFRS tag set doesn't carry a direct equivalent (e.g., COGS,
# segment EBIT, restructuring breakouts, retirement obligations), the row is
# left blank for the modeler.
# ---------------------------------------------------------------------------
INCOME_STATEMENT: tuple[Mapping, ...] = (
    Mapping(row=114, tags=("Revenue",), kind="duration"),
    Mapping(row=125, tags=("OtherOperatingIncomeExpense",), kind="duration"),
    Mapping(row=126, tags=("ProfitLossFromOperatingActivities",), kind="duration"),
    # FinanceCosts in TFI's XBRL flipped sign in FY21/FY22 (positive-as-negative).
    # Take absolute value so "Interest expense" stays a positive number.
    Mapping(row=127, tags=("FinanceCosts",), kind="duration", abs_value=True),
    Mapping(row=128, tags=("FinanceIncome",), kind="duration", abs_value=True),
    Mapping(row=130, tags=("ProfitLossBeforeTax",), kind="duration"),
    Mapping(row=131, tags=("IncomeTaxExpenseContinuingOperations",), kind="duration"),
    Mapping(
        row=133,
        tags=("ProfitLossAttributableToOwnersOfParent", "ProfitLoss"),
        kind="duration",
    ),
    # Per-share data: no $M scaling.
    Mapping(row=136, tags=("BasicEarningsLossPerShare",), kind="duration", scale=1),
    Mapping(row=137, tags=("DilutedEarningsLossPerShare",), kind="duration", scale=1),
    # Weighted-average share counts ('000): convert raw shares to thousands.
    Mapping(row=138, tags=("WeightedAverageShares",), kind="duration", scale=1_000),
    Mapping(row=139, tags=("AdjustedWeightedAverageShares",), kind="duration", scale=1_000),
)

CASH_FLOW: tuple[Mapping, ...] = (
    Mapping(row=175, tags=("ProfitLossAttributableToOwnersOfParent", "ProfitLoss"), kind="duration"),
    Mapping(row=176, tags=("AdjustmentsForDepreciationExpense",), kind="duration"),
    Mapping(row=177, tags=("AdjustmentsForAmortisationExpense",), kind="duration"),
    Mapping(row=178, tags=("AdjustmentsForSharebasedPayments",), kind="duration"),
    Mapping(row=180, tags=("AdjustmentsForDecreaseIncreaseInTradeAndOtherReceivables",), kind="duration"),
    Mapping(row=181, tags=("AdjustmentsForDecreaseIncreaseInInventories",), kind="duration"),
    Mapping(row=182, tags=("AdjustmentsForIncreaseDecreaseInTradeAndOtherPayables",), kind="duration"),
    Mapping(row=186, tags=("CashFlowsFromUsedInOperatingActivities",), kind="duration"),
    # Capex reported positive in XBRL; template treats it as a cash use (negative).
    Mapping(
        row=189,
        tags=("PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities",),
        kind="duration",
        sign=-1,
    ),
    # Acquisitions reported positive (cash used); negate for the template.
    Mapping(
        row=190,
        tags=("CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities",),
        kind="duration",
        sign=-1,
    ),
    Mapping(
        row=193,
        tags=("CashFlowsFromUsedInInvestingActivitiesContinuingOperations",),
        kind="duration",
    ),
    # Dividends reported positive (cash use); template convention is negative.
    Mapping(row=198, tags=("DividendsPaidClassifiedAsFinancingActivities",), kind="duration", sign=-1),
    Mapping(row=199, tags=("PaymentsToAcquireOrRedeemEntitysShares",), kind="duration", sign=-1),
    Mapping(
        row=202,
        tags=("CashFlowsFromUsedInFinancingActivitiesContinuingOperations",),
        kind="duration",
    ),
    Mapping(row=205, tags=("IncreaseDecreaseInCashAndCashEquivalents",), kind="duration"),
)

BALANCE_SHEET: tuple[Mapping, ...] = (
    Mapping(row=226, tags=("CashAndCashEquivalents",), kind="instant"),
    Mapping(row=227, tags=("TradeAndOtherCurrentReceivables",), kind="instant"),
    Mapping(row=228, tags=("Inventories",), kind="instant"),
    Mapping(row=230, tags=("CurrentAssets",), kind="instant"),
    Mapping(row=231, tags=("PropertyPlantAndEquipment",), kind="instant"),
    # Goodwill standalone disappears after FY22; the combined Goodwill +
    # Intangibles total is in IntangibleAssetsAndGoodwill across all years.
    Mapping(row=232, tags=("Goodwill",), kind="instant"),
    Mapping(row=233, tags=("IntangibleAssetsAndGoodwill",), kind="instant"),
    Mapping(row=234, tags=("RightofuseAssets",), kind="instant"),
    Mapping(row=235, tags=("DeferredTaxAssets",), kind="instant"),
    Mapping(row=236, tags=("OtherNoncurrentAssets",), kind="instant"),
    Mapping(row=237, tags=("Assets",), kind="instant"),
    Mapping(row=241, tags=("CurrentPortionOfLongtermBorrowings",), kind="instant"),
    Mapping(row=243, tags=("TradeAndOtherCurrentPayables",), kind="instant"),
    Mapping(row=247, tags=("CurrentLiabilities",), kind="instant"),
    Mapping(row=248, tags=("LongtermBorrowings",), kind="instant"),
    # Operating-lease liabilities: template row 249 is non-current portion.
    Mapping(row=249, tags=("NoncurrentLeaseLiabilities",), kind="instant"),
    Mapping(row=251, tags=("DeferredTaxLiabilities",), kind="instant"),
    Mapping(row=253, tags=("Liabilities",), kind="instant"),
    Mapping(row=260, tags=("Equity",), kind="instant"),
    Mapping(row=261, tags=("EquityAndLiabilities",), kind="instant"),
)

ALL_MAPPINGS: tuple[Mapping, ...] = INCOME_STATEMENT + CASH_FLOW + BALANCE_SHEET


# ---------------------------------------------------------------------------
# EDGAR fetcher
# ---------------------------------------------------------------------------

def fetch_facts(cache_path: Path | None = None) -> dict:
    """Fetch the EDGAR XBRL Company Facts JSON for TFI International.

    If ``cache_path`` is provided and exists, it is read instead of going
    over the network. The fetched payload is written there on success.
    """
    if cache_path and cache_path.exists():
        return json.loads(cache_path.read_text())
    req = urllib.request.Request(FACTS_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = resp.read().decode("utf-8")
    if cache_path:
        cache_path.write_text(payload)
    return json.loads(payload)


# ---------------------------------------------------------------------------
# Fact extraction
# ---------------------------------------------------------------------------

def _is_full_year_duration(entry: dict, year: int) -> bool:
    start = entry.get("start", "")
    end = entry.get("end", "")
    return (
        start == f"{year}-01-01"
        and end == f"{year}-12-31"
        and entry.get("fp") == "FY"
    )


def _is_year_end_instant(entry: dict, year: int) -> bool:
    return entry.get("end") == f"{year}-12-31" and entry.get("fp") == "FY"


def value_for_year(facts: dict, tag: str, year: int, kind: str) -> float | None:
    """Return the most-recently-filed value of ``tag`` for fiscal ``year``.

    ``kind`` is ``"duration"`` (period flow) or ``"instant"`` (balance).
    Returns ``None`` if no matching entry exists.
    """
    ifrs = facts.get("facts", {}).get("ifrs-full", {})
    if tag not in ifrs:
        return None
    units = ifrs[tag]["units"]
    # Prefer USD; fall back to USD/shares or shares for per-share/share-count tags.
    for unit_name in ("USD", "USD/shares", "shares"):
        if unit_name not in units:
            continue
        match_fn = _is_full_year_duration if kind == "duration" else _is_year_end_instant
        candidates = [e for e in units[unit_name] if match_fn(e, year)]
        if not candidates:
            continue
        # Pick the latest-filed entry (most recent restatement wins).
        best = max(candidates, key=lambda e: e.get("filed", ""))
        return float(best["val"])
    return None


def resolve_value(facts: dict, mapping: Mapping, year: int) -> float | None:
    """Walk a mapping's tag list, return the first hit with the scale/sign applied."""
    for tag in mapping.tags:
        raw = value_for_year(facts, tag, year, mapping.kind)
        if raw is None:
            continue
        if mapping.abs_value:
            raw = abs(raw)
        return mapping.sign * raw / mapping.scale
    return None


# ---------------------------------------------------------------------------
# Workbook write
# ---------------------------------------------------------------------------

FISCAL_YEARS = range(2020, 2026)


def populate(
    workbook_path: str | Path,
    *,
    years: Iterable[int] = FISCAL_YEARS,
    facts_cache: Path | None = None,
) -> dict[tuple[int, int], float]:
    """Populate ``workbook_path`` in place with TFI's IFRS historicals.

    Returns a dict of ``{(year, row): value}`` actually written, so callers
    can audit coverage.
    """
    workbook_path = Path(workbook_path)
    facts = fetch_facts(cache_path=facts_cache)
    wb = load_workbook(workbook_path)
    ws = wb["Model"]

    written: dict[tuple[int, int], float] = {}
    for year in years:
        col = fy_total_col(year)
        for m in ALL_MAPPINGS:
            v = resolve_value(facts, m, year)
            if v is None:
                continue
            ws.cell(row=m.row, column=col).value = v
            written[(year, m.row)] = v

    wb.save(workbook_path)
    return written


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Populate TFI International historicals into a model template."
    )
    parser.add_argument(
        "workbook",
        type=Path,
        help="Path to the TFI model .xlsx (will be modified in place).",
    )
    parser.add_argument(
        "--facts-cache",
        type=Path,
        default=None,
        help="Optional path to cache the EDGAR Company Facts JSON.",
    )
    args = parser.parse_args(argv)

    written = populate(args.workbook, facts_cache=args.facts_cache)
    print(f"Wrote {len(written)} cells across {len({y for y, _ in written})} fiscal years.")
    by_year: dict[int, int] = {}
    for (y, _), _ in written.items():
        by_year[y] = by_year.get(y, 0) + 1
    for y in sorted(by_year):
        print(f"  FY{y}: {by_year[y]} cells")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
