"""Populate TFI International consolidated historicals (FY20-FY25) into the
template generated by the financial_model builder.

TFI International files as a Canadian foreign private issuer (Form 40-F,
CIK 0001588823) under IFRS. The populator combines two EDGAR data sources:

  1. The standardized ifrs-full tags from the Company Facts JSON API
     (data.sec.gov) for the consolidated income statement, cash flow
     statement, and balance sheet.
  2. The per-filing "Segment Reporting (Details)" rendered R-files
     (www.sec.gov/Archives/.../R??.htm) for per-segment revenue and
     operating income, since segment breakouts are not in the standard
     IFRS taxonomy.

Segment-structure mapping:
  - FY20-FY23: 4 reportable segments (Package and Courier, LTL,
    Truckload, Logistics) -> the template's legacy 4-segment block.
  - FY24-FY25: 3 reportable segments (LTL, Truckload, Logistics) ->
    the template's current 3-segment block. Package and Courier was
    rolled into LTL in the FY24 40-F (confirmed by the FY23 restated
    comparative, where LTL revenue jumped ~$580M = prior-year P&C).

Known data quirks the populator preserves as-tagged:
  - FY24 CashAndCashEquivalents is tagged as 0 in both the original and
    the FY25 40-F restated comparative. The actual year-end balance has
    to be entered manually from the BS in the 40-F PDF.
  - FY21 / FY22 FinanceCosts are tagged with a negative sign in TFI's
    XBRL (an inconsistency between filings). The populator takes abs()
    so "Interest expense" remains positive.
  - Standalone Goodwill is only tagged through FY22. FY23+ rolls into
    IntangibleAssetsAndGoodwill -- that combined value lands in the
    template's "Intangible assets, net" row.
"""

from __future__ import annotations

import html
import json
import re
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

TFI_CIK = "0001588823"
FACTS_URL = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{TFI_CIK}.json"
USER_AGENT = "industrials-optima/0.1 (payton.liske@gmail.com)"

# Per the Moog template layout: FY10 sits at column G (index 7), each
# subsequent year occupies five columns (Q1..Q4 + FY total), so FYn's
# total column is at index 7 + 5*(n - 10) where n is the 2-digit year.
# Accept either 2- or 4-digit input to avoid foot-guns.
def fy_total_col(fy: int) -> int:
    yy = fy - 2000 if fy >= 1900 else fy
    return 7 + 5 * (yy - 10)


# A single mapping entry from a template row to one (or more) ifrs-full tags.
@dataclass
class Mapping:
    row: int
    tags: tuple[str, ...]    # try each tag in order; first hit wins
    kind: str                 # "duration" (period-flow) or "instant" (point-in-time)
    scale: float = 1_000_000  # divide raw USD by this; use 1 for per-share, 1000 for share counts
    sign: int = 1             # multiply by this (use -1 to negate)
    abs_value: bool = False   # take abs() before scaling (for tags with inconsistent sign)


# ---------------------------------------------------------------------------
# Mapping: ifrs-full tag -> Moog template row.
#
# Where the IFRS tag set doesn't carry a direct equivalent (e.g., COGS,
# segment EBIT, restructuring breakouts, retirement obligations), the row is
# left blank for the modeler.
# ---------------------------------------------------------------------------
INCOME_STATEMENT: tuple[Mapping, ...] = (
    Mapping(row=114, tags=("Revenue",), kind="duration"),
    Mapping(row=125, tags=("OtherOperatingIncomeExpense",), kind="duration"),
    Mapping(row=126, tags=("ProfitLossFromOperatingActivities",), kind="duration"),
    # FinanceCosts in TFI's XBRL flipped sign in FY21/FY22 (positive-as-negative).
    # Take absolute value so "Interest expense" stays a positive number.
    Mapping(row=127, tags=("FinanceCosts",), kind="duration", abs_value=True),
    Mapping(row=128, tags=("FinanceIncome",), kind="duration", abs_value=True),
    Mapping(row=130, tags=("ProfitLossBeforeTax",), kind="duration"),
    Mapping(row=131, tags=("IncomeTaxExpenseContinuingOperations",), kind="duration"),
    Mapping(
        row=133,
        tags=("ProfitLossAttributableToOwnersOfParent", "ProfitLoss"),
        kind="duration",
    ),
    # Per-share data: no $M scaling.
    Mapping(row=136, tags=("BasicEarningsLossPerShare",), kind="duration", scale=1),
    Mapping(row=137, tags=("DilutedEarningsLossPerShare",), kind="duration", scale=1),
    # Weighted-average share counts ('000): convert raw shares to thousands.
    Mapping(row=138, tags=("WeightedAverageShares",), kind="duration", scale=1_000),
    Mapping(row=139, tags=("AdjustedWeightedAverageShares",), kind="duration", scale=1_000),
)

CASH_FLOW: tuple[Mapping, ...] = (
    Mapping(row=175, tags=("ProfitLossAttributableToOwnersOfParent", "ProfitLoss"), kind="duration"),
    Mapping(row=176, tags=("AdjustmentsForDepreciationExpense",), kind="duration"),
    Mapping(row=177, tags=("AdjustmentsForAmortisationExpense",), kind="duration"),
    Mapping(row=178, tags=("AdjustmentsForSharebasedPayments",), kind="duration"),
    Mapping(row=180, tags=("AdjustmentsForDecreaseIncreaseInTradeAndOtherReceivables",), kind="duration"),
    Mapping(row=181, tags=("AdjustmentsForDecreaseIncreaseInInventories",), kind="duration"),
    Mapping(row=182, tags=("AdjustmentsForIncreaseDecreaseInTradeAndOtherPayables",), kind="duration"),
    Mapping(row=186, tags=("CashFlowsFromUsedInOperatingActivities",), kind="duration"),
    # Capex reported positive in XBRL; template treats it as a cash use (negative).
    Mapping(
        row=189,
        tags=("PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities",),
        kind="duration",
        sign=-1,
    ),
    # Acquisitions reported positive (cash used); negate for the template.
    Mapping(
        row=190,
        tags=("CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities",),
        kind="duration",
        sign=-1,
    ),
    Mapping(
        row=193,
        tags=("CashFlowsFromUsedInInvestingActivitiesContinuingOperations",),
        kind="duration",
    ),
    # Dividends reported positive (cash use); template convention is negative.
    Mapping(row=198, tags=("DividendsPaidClassifiedAsFinancingActivities",), kind="duration", sign=-1),
    Mapping(row=199, tags=("PaymentsToAcquireOrRedeemEntitysShares",), kind="duration", sign=-1),
    Mapping(
        row=202,
        tags=("CashFlowsFromUsedInFinancingActivitiesContinuingOperations",),
        kind="duration",
    ),
    Mapping(row=205, tags=("IncreaseDecreaseInCashAndCashEquivalents",), kind="duration"),
)

BALANCE_SHEET: tuple[Mapping, ...] = (
    Mapping(row=226, tags=("CashAndCashEquivalents",), kind="instant"),
    Mapping(row=227, tags=("TradeAndOtherCurrentReceivables",), kind="instant"),
    Mapping(row=228, tags=("Inventories",), kind="instant"),
    Mapping(row=230, tags=("CurrentAssets",), kind="instant"),
    Mapping(row=231, tags=("PropertyPlantAndEquipment",), kind="instant"),
    # Goodwill standalone disappears after FY22; the combined Goodwill +
    # Intangibles total is in IntangibleAssetsAndGoodwill across all years.
    Mapping(row=232, tags=("Goodwill",), kind="instant"),
    Mapping(row=233, tags=("IntangibleAssetsAndGoodwill",), kind="instant"),
    Mapping(row=234, tags=("RightofuseAssets",), kind="instant"),
    Mapping(row=235, tags=("DeferredTaxAssets",), kind="instant"),
    Mapping(row=236, tags=("OtherNoncurrentAssets",), kind="instant"),
    Mapping(row=237, tags=("Assets",), kind="instant"),
    Mapping(row=241, tags=("CurrentPortionOfLongtermBorrowings",), kind="instant"),
    Mapping(row=243, tags=("TradeAndOtherCurrentPayables",), kind="instant"),
    Mapping(row=247, tags=("CurrentLiabilities",), kind="instant"),
    Mapping(row=248, tags=("LongtermBorrowings",), kind="instant"),
    # Operating-lease liabilities: template row 249 is non-current portion.
    Mapping(row=249, tags=("NoncurrentLeaseLiabilities",), kind="instant"),
    Mapping(row=251, tags=("DeferredTaxLiabilities",), kind="instant"),
    Mapping(row=253, tags=("Liabilities",), kind="instant"),
    Mapping(row=260, tags=("Equity",), kind="instant"),
    Mapping(row=261, tags=("EquityAndLiabilities",), kind="instant"),
)

ALL_MAPPINGS: tuple[Mapping, ...] = INCOME_STATEMENT + CASH_FLOW + BALANCE_SHEET


# ---------------------------------------------------------------------------
# EDGAR fetcher
# ---------------------------------------------------------------------------

def fetch_facts(cache_path: Path | None = None) -> dict:
    """Fetch the EDGAR XBRL Company Facts JSON for TFI International.

    If ``cache_path`` is provided and exists, it is read instead of going
    over the network. The fetched payload is written there on success.
    """
    if cache_path and cache_path.exists():
        return json.loads(cache_path.read_text())
    req = urllib.request.Request(FACTS_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = resp.read().decode("utf-8")
    if cache_path:
        cache_path.write_text(payload)
    return json.loads(payload)


# ---------------------------------------------------------------------------
# Fact extraction
# ---------------------------------------------------------------------------

def _is_full_year_duration(entry: dict, year: int) -> bool:
    start = entry.get("start", "")
    end = entry.get("end", "")
    return (
        start == f"{year}-01-01"
        and end == f"{year}-12-31"
        and entry.get("fp") == "FY"
    )


def _is_year_end_instant(entry: dict, year: int) -> bool:
    return entry.get("end") == f"{year}-12-31" and entry.get("fp") == "FY"


def value_for_year(facts: dict, tag: str, year: int, kind: str) -> float | None:
    """Return the most-recently-filed value of ``tag`` for fiscal ``year``.

    ``kind`` is ``"duration"`` (period flow) or ``"instant"`` (balance).
    Returns ``None`` if no matching entry exists.
    """
    ifrs = facts.get("facts", {}).get("ifrs-full", {})
    if tag not in ifrs:
        return None
    units = ifrs[tag]["units"]
    # Prefer USD; fall back to USD/shares or shares for per-share/share-count tags.
    for unit_name in ("USD", "USD/shares", "shares"):
        if unit_name not in units:
            continue
        match_fn = _is_full_year_duration if kind == "duration" else _is_year_end_instant
        candidates = [e for e in units[unit_name] if match_fn(e, year)]
        if not candidates:
            continue
        # Pick the latest-filed entry (most recent restatement wins).
        best = max(candidates, key=lambda e: e.get("filed", ""))
        return float(best["val"])
    return None


def resolve_value(facts: dict, mapping: Mapping, year: int) -> float | None:
    """Walk a mapping's tag list, return the first hit with the scale/sign applied."""
    for tag in mapping.tags:
        raw = value_for_year(facts, tag, year, mapping.kind)
        if raw is None:
            continue
        if mapping.abs_value:
            raw = abs(raw)
        return mapping.sign * raw / mapping.scale
    return None


# ---------------------------------------------------------------------------
# Segment data: parsed from each year's 40-F "Segment Reporting (Details)"
# rendered XBRL R-file. The structured ifrs-full taxonomy doesn't break out
# per-segment revenue/EBIT, so we go straight to the rendered tables.
#
# Mapping rationale: TFI reported FOUR segments through FY23 (P&C + LTL + TL
# + Logistics) and consolidated to THREE in FY24+ (P&C rolled into LTL,
# confirmed by the FY23 restated comparative in the FY24 40-F where LTL
# revenue jumps by ~$580M = prior-year P&C). FY20-FY23 therefore land in
# the template's legacy 4-segment block (rows 11/19/26/33); FY24-FY25 land
# in the current 3-segment block (rows 53/64/75).
# ---------------------------------------------------------------------------

EDGAR_FILING_BASE = f"https://www.sec.gov/Archives/edgar/data/{int(TFI_CIK)}"

# (accession, segment-results R-file) per fiscal year (mined from each
# filing's FilingSummary.xml — "Information Regarding Results of Reportable
# Segment (Details)").
SEGMENT_REPORT_FILES: dict[int, tuple[str, str]] = {
    2020: ("0001564590-21-006695", "R67.htm"),
    2021: ("0001193125-22-074819", "R64.htm"),
    2022: ("0001193125-23-046368", "R65.htm"),
    2023: ("0000950170-24-016307", "R64.htm"),
    2024: ("0000950170-25-023200", "R65.htm"),
    2025: ("0001193125-26-054689", "R64.htm"),
}

# Legacy block (rows 11/19/26/33): segment header at the named row, Net
# sales at +1, Operating profit at +2.
LEGACY_SEGMENT_ROWS: dict[str, int] = {
    "Package and Courier": 11,
    "Less-Than-Truckload": 19,
    "Truckload": 26,
    "Logistics": 33,
}
LEGACY_LINE_OFFSETS: dict[str, int] = {
    "Total revenue": 1,            # -> Net sales
    "Operating income (loss)": 2,  # -> Operating profit
}

# Current block (rows 53/64/75): segment header at the named row, Net sales
# at +1, EBIT at +3.
CURRENT_SEGMENT_ROWS: dict[str, int] = {
    "Less-Than-Truckload": 53,
    "Truckload": 64,
    "Logistics": 75,
}
CURRENT_LINE_OFFSETS: dict[str, int] = {
    "Total revenue": 1,            # -> Net sales
    "Operating income (loss)": 3,  # -> EBIT
}


def fetch_segment_report(fy: int, cache_dir: Path | None = None) -> str:
    """Fetch the segment-results R-file HTML for fiscal year ``fy``.

    EDGAR rate-limits sequential requests; retry with exponential backoff
    on 503 up to four attempts.
    """
    acc, htm_name = SEGMENT_REPORT_FILES[fy]
    if cache_dir:
        cached = cache_dir / f"segment_{fy}.htm"
        if cached.exists():
            return cached.read_text()
    url = f"{EDGAR_FILING_BASE}/{acc.replace('-', '')}/{htm_name}"
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    delay = 2.0
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                text = resp.read().decode("utf-8")
            if cache_dir:
                cache_dir.mkdir(parents=True, exist_ok=True)
                (cache_dir / f"segment_{fy}.htm").write_text(text)
            return text
        except urllib.error.HTTPError as e:
            if e.code != 503 or attempt == 3:
                raise
            time.sleep(delay)
            delay *= 2
    raise RuntimeError(f"Unreachable: failed to fetch segment R-file for FY{fy}")


def _parse_cell(s: str) -> float | None:
    """Parse a numeric cell: '$ 6,913,039' / '(46,061)' / '$ (124)' / '—'."""
    if not s:
        return None
    s = s.replace("$", "").replace(",", "").strip()
    s = re.sub(r"\[[0-9,]+\]", "", s).strip()  # drop footnote markers [1], [2,3]
    if s in ("", "—", "-", "–"):
        return None
    neg = s.startswith("(") and s.endswith(")")
    if neg:
        s = s[1:-1].strip()
    try:
        v = float(s)
    except ValueError:
        return None
    return -v if neg else v


def parse_segment_html(html_text: str) -> tuple[list[int], dict[str, dict[str, list[float | None]]]]:
    """Parse a 40-F segment R-file. Returns ``(years, segments)`` where
    ``years`` is the column labels (most recent first) and ``segments`` maps
    each segment name (e.g. ``"Less-Than-Truckload"``) to ``{line_item:
    values_per_column}``.
    """
    html_text = re.sub(r"<style[^>]*>.*?</style>", "", html_text, flags=re.S)
    html_text = re.sub(r"<script[^>]*>.*?</script>", "", html_text, flags=re.S)

    rows: list[list[str]] = []
    for tr in re.finditer(r"<tr[^>]*>(.*?)</tr>", html_text, flags=re.S):
        cells: list[str] = []
        for td in re.finditer(r"<t[hd][^>]*>(.*?)</t[hd]>", tr.group(1), flags=re.S):
            txt = re.sub(r"<[^>]+>", " ", td.group(1))
            txt = html.unescape(txt).replace("\xa0", " ").strip()
            txt = re.sub(r"\s+", " ", txt)
            cells.append(txt)
        if cells:
            rows.append(cells)

    # Year columns appear in the first few header rows as 'Dec. 31, YYYY'.
    years: list[int] = []
    for row in rows[:5]:
        for cell in row:
            m = re.search(r"(20\d{2})", cell)
            if m and "Dec" in cell:
                y = int(m.group(1))
                if y not in years:
                    years.append(y)

    segments: dict[str, dict[str, list[float | None]]] = {"Total": {}}
    current = "Total"
    for row in rows:
        first = row[0] if row else ""
        if first.startswith("Operating Segments |"):
            current = first.split("|", 1)[1].strip()
            segments.setdefault(current, {})
            continue
        if first in ("Corporate", "Eliminations") and not any(
            re.search(r"\d", c) for c in row[1:3]
        ):
            current = first
            segments.setdefault(current, {})
            continue
        nums = [_parse_cell(c) for c in row[1:]]
        if any(n is not None for n in nums):
            segments[current][first] = nums
    return years, segments


def _values_by_year(years: list[int], vals: list[float | None]) -> dict[int, float]:
    """Strip empty cells, then positionally align remaining numeric cells with the year header."""
    filtered = [v for v in vals if v is not None]
    return {y: v for y, v in zip(years, filtered)}


def populate_segments(
    workbook_path: str | Path,
    *,
    segment_cache_dir: Path | None = None,
) -> dict[tuple[int, int, str], float]:
    """Populate segment P&L blocks (legacy FY20-FY23 + current FY24-FY25).

    Returns ``{(year, row, segment_name): value}``.
    """
    workbook_path = Path(workbook_path)
    wb = load_workbook(workbook_path)
    ws = wb["Model"]
    written: dict[tuple[int, int, str], float] = {}

    for idx, fy in enumerate(SEGMENT_REPORT_FILES):
        if idx > 0:
            # Pace successive EDGAR fetches; respects the public-data limit
            # and is a no-op when the cache already has the file.
            time.sleep(0.25)
        text = fetch_segment_report(fy, cache_dir=segment_cache_dir)
        years, segs = parse_segment_html(text)
        # Decide which block this filing belongs to based on its segment set.
        is_legacy = "Package and Courier" in segs
        seg_rows = LEGACY_SEGMENT_ROWS if is_legacy else CURRENT_SEGMENT_ROWS
        line_offsets = LEGACY_LINE_OFFSETS if is_legacy else CURRENT_LINE_OFFSETS

        # Each filing's current year always gets stamped; the FY20 filing is
        # also the only EDGAR source for FY19 segment values (its R-file has
        # FY20 + FY19 + FY18 columns), so harvest the prior-year column there
        # to unlock the FY20 segment y/y% calculations.
        target_years = [fy] + ([fy - 1] if fy == 2020 else [])

        for target_fy in target_years:
            col = fy_total_col(target_fy)
            for seg_name, seg_row in seg_rows.items():
                if seg_name not in segs:
                    continue
                for label, offset in line_offsets.items():
                    line_vals = segs[seg_name].get(label)
                    if not line_vals:
                        continue
                    vals_by_yr = _values_by_year(years, line_vals)
                    if target_fy not in vals_by_yr:
                        continue
                    # R-files report in $ thousands; template uses $ millions.
                    v = vals_by_yr[target_fy] / 1_000.0
                    ws.cell(row=seg_row + offset, column=col).value = v
                    written[(target_fy, seg_row + offset, seg_name)] = v

    wb.save(workbook_path)
    return written


# ---------------------------------------------------------------------------
# Formula completions
#
# The Moog source template carries formulas only for the year ranges Moog
# itself used (legacy block FY11-FY21/FY22, current block FY22-FY25). For
# TFI's data shape and reporting history we need to fill the gaps, point
# cross-block transitions at the legacy block (with P&C add-back for LTL),
# and repoint a couple of rows whose source formula targets an upstream
# cell TFI doesn't have data for.
#
# Categories below:
#   1. y/y% completions (covered Sales y/y% and EBIT y/y%)
#   2. Legacy Group Total SUM extensions (4 segments, through FY23)
#   3. Cross-block FY24 overrides for the current block (y/y% + Inc EBIT
#      + Group totals so the FY24 group y/y% has a real denominator)
#   4. Other derived metrics: legacy Op margin % gap-fill, current-block
#      cross-block Incremental EBIT, Adj EBIT % / Inc OP margin repointed
#      to GAAP EBIT (row 126) since TFI has no GAAP->Adj bridge.
#
# Backlog y/y%, book-to-bill, gross margin / R&D % / SG&A % / DIO / DPO
# are intentionally untouched -- TFI is a logistics business and either
# the metric isn't reported (backlog/B:B) or the underlying line item
# isn't broken out in the IFRS taxonomy (no COGS / R&D / SG&A split).
# ---------------------------------------------------------------------------

_FORMULA_OVERRIDES: tuple[tuple[str, str], ...] = (
    # ---- (1) Legacy block segment Sales y/y% (FY22 + FY23 backfill) -------
    ("BO14", '=IFERROR(BO12/BJ12-1,"")'),   # P&C
    ("BT14", '=IFERROR(BT12/BO12-1,"")'),
    ("BO22", '=IFERROR(BO20/BJ20-1,"")'),   # LTL legacy
    ("BT22", '=IFERROR(BT20/BO20-1,"")'),
    ("BO29", '=IFERROR(BO27/BJ27-1,"")'),   # Truckload legacy
    ("BT29", '=IFERROR(BT27/BO27-1,"")'),

    # ---- (2) Legacy Group Total -- extend SUM to 4 segments and to FY23 ---
    ("BE44", "=BE12+BE20+BE27+BE34"),
    ("BJ44", "=BJ12+BJ20+BJ27+BJ34"),
    ("BO44", "=BO12+BO20+BO27+BO34"),
    ("BT44", "=BT12+BT20+BT27+BT34"),
    ("BE45", "=BE13+BE21+BE28+BE35"),
    ("BJ45", "=BJ13+BJ21+BJ28+BJ35"),
    ("BO45", "=BO13+BO21+BO28+BO35"),
    ("BT45", "=BT13+BT21+BT28+BT35"),
    ("BT46", '=IFERROR(BT44/BO44-1,"")'),   # FY23 Group Sales y/y%

    # ---- (3) Current block FY24 cross-block overrides --------------------
    # Sales y/y% and EBIT y/y%: source refs empty FY23 current-block cells.
    # LTL adds back legacy P&C since TFI rolled P&C into LTL in FY24.
    ("BY55", '=IFERROR(BY54/(BT20+BT12)-1,"")'),
    ("BY57", '=IFERROR(BY56/(BT21+BT13)-1,"")'),
    ("BY66", '=IFERROR(BY65/BT27-1,"")'),
    ("BY68", '=IFERROR(BY67/BT28-1,"")'),
    ("BY77", '=IFERROR(BY76/BT34-1,"")'),
    ("BY79", '=IFERROR(BY78/BT35-1,"")'),

    # Current Group totals for FY20-FY23: repoint at the legacy Group Total
    # (rows 44 = sum of 4-segment Net sales, 45 = sum of 4-segment Op profit).
    # Source had row 98 = =row114 (consolidated rev incl elims) for FY20-FY22
    # and segment-sum-of-empties for FY23, and row 102 = None for FY20/FY21
    # and segment-sum-of-empties from FY22. Repointing both to the legacy
    # group totals keeps the entire current Group block on a single
    # "segments only, ex Corporate" basis -- the same basis the current
    # block uses for FY24-FY25 -- so every downstream y/y% / EBIT % / Inc
    # EBIT computation stays apples-to-apples across the transition year.
    ("BE98",  "=BE44"), ("BJ98",  "=BJ44"),
    ("BO98",  "=BO44"), ("BT98",  "=BT44"),
    ("BE102", "=BE45"), ("BJ102", "=BJ45"),
    ("BO102", "=BO45"), ("BT102", "=BT45"),

    # ---- (4) Other derived-metric completions ----------------------------
    # Legacy block Op margin % FY23 -- source covered FY11-FY22 only.
    ("BT15", "=BT13/BT12"),                  # P&C
    ("BT23", "=BT21/BT20"),                  # LTL legacy
    ("BT30", "=BT28/BT27"),                  # Truckload legacy
    ("BT47", "=BT45/BT44"),                  # Legacy Group

    # Legacy Logistics Op margin (row 36): source had a buggy y/y-style
    # formula (=row34/prior_row34-1) labeled as a margin and only through
    # FY17; rewrite correctly for the populated FY20-FY23 window.
    ("BE36", "=BE35/BE34"),
    ("BJ36", "=BJ35/BJ34"),
    ("BO36", "=BO35/BO34"),
    ("BT36", "=BT35/BT34"),

    # Current block FY24 Incremental EBIT -- same cross-block pattern as
    # y/y%, including the P&C add-back for LTL.
    ("BY59",  '=IFERROR((BY56-(BT21+BT13))/(BY54-(BT20+BT12)),"")'),  # LTL
    ("BY70",  '=IFERROR((BY67-BT28)/(BY65-BT27),"")'),                 # TL
    ("BY81",  '=IFERROR((BY78-BT35)/(BY76-BT34),"")'),                 # Logistics
    ("BY105", '=IFERROR((BY102-BT45)/(BY98-BT44),"")'),                # Group

    # Adj EBIT % (row 168) and Incremental OP margin (row 170): source
    # references row 148 (Adjusted operating profit). TFI has no
    # GAAP->Adjusted bridge in the IFRS taxonomy, so repoint at row 126
    # (GAAP EBIT) -- the labels are now effectively "EBIT %" and
    # "Incremental EBIT margin", a useful proxy.
    ("BE168", "=BE126/BE114"), ("BJ168", "=BJ126/BJ114"),
    ("BO168", "=BO126/BO114"), ("BT168", "=BT126/BT114"),
    ("BY168", "=BY126/BY114"), ("CD168", "=CD126/CD114"),
    ("BE170", "=(BE126-AZ126)/(BE114-AZ114)"),
    ("BJ170", "=(BJ126-BE126)/(BJ114-BE114)"),
    ("BO170", "=(BO126-BJ126)/(BO114-BJ114)"),
    ("BT170", "=(BT126-BO126)/(BT114-BO114)"),
    ("BY170", "=(BY126-BT126)/(BY114-BT114)"),
    ("CD170", "=(CD126-BY126)/(CD114-BY114)"),
)


def add_yoy_formulas(workbook_path: str | Path) -> int:
    """Apply the TFI-specific formula completions to ``workbook_path``.

    Covers y/y% backfill, legacy Group Total extensions, cross-block FY24
    overrides for the current block, legacy Op margin gap-fill (including
    the Logistics row whose source formula was buggy), current-block
    Incremental EBIT cross-block overrides, and Adj-EBIT-%/Inc-OP-margin
    repoints to GAAP EBIT (TFI has no GAAP->Adj bridge).

    Returns the number of cells written.
    """
    workbook_path = Path(workbook_path)
    wb = load_workbook(workbook_path)
    ws = wb["Model"]
    for cell_ref, formula in _FORMULA_OVERRIDES:
        ws[cell_ref] = formula
    wb.save(workbook_path)
    return len(_FORMULA_OVERRIDES)


# ---------------------------------------------------------------------------
# Per-segment operational detail
#
# TFI's 40-F "Segment Reporting (Details)" note discloses a full operating
# decomposition per segment (revenue ex/incl fuel, the four expense
# buckets, gains on dispositions, period-end intangibles / total assets /
# total liabilities, and capex). The structured XBRL doesn't expose
# operational KPIs (shipments, OR%, etc.) -- only the financial breakdown.
#
# Time range: the 3-segment structure was introduced in the FY24 40-F, so
# we go back as far as the most recent restated comparative -- FY23 from
# the FY24 40-F's prior-year column, FY24-FY25 from the FY25 40-F.
#
# Layout: a section below the main Model area (row 376+), per-segment
# blocks with values in the existing FY columns (BT=FY23, BY=FY24,
# CD=FY25). Doesn't disturb the existing segment-block rows above.
# ---------------------------------------------------------------------------

OPERATIONAL_SECTION_TITLE_ROW = 376
OPERATIONAL_FIRST_BLOCK_ROW = 380
OPERATIONAL_BLOCK_STEP = 16

# Order matters -- it's the on-sheet rendering order under each segment.
OPERATIONAL_LINE_ITEMS: tuple[tuple[str, str], ...] = (
    # (template label written in column B, line label as it appears in the R-file)
    ("  Revenue (ex-fuel)",                          "Revenue"),
    ("  Fuel surcharge",                             "Fuel surcharge"),
    ("  Total revenue",                              "Total revenue"),
    ("  Operating income (loss)",                    "Operating income (loss)"),
    ("  Materials and services expenses",            "Materials and services expenses"),
    ("  Personnel expenses",                         "Personnel expenses"),
    ("  Other operating expenses",                   "Other operating expenses"),
    ("  Depreciation and amortization",              "Depreciation and amortization"),
    ("  Gain (loss) on sale of land and buildings",  "Gain (loss) on sale of land and buildings"),
    ("  Gain on sale of held-for-sale assets",       "Gain, net of impairment, on sale of assets held for sale"),
    ("  Intangible assets (BS, period-end)",         "Intangible assets"),
    ("  Total assets (BS, period-end)",              "Total assets"),
    ("  Total liabilities (BS, period-end)",         "Total liabilities"),
    ("  Additions to PP&E (capex)",                  "Additions to property and equipment"),
)

OPERATIONAL_SEGMENTS: tuple[str, ...] = ("Less-Than-Truckload", "Truckload", "Logistics")

# Per fiscal year, the filing whose R-file holds the latest restated values
# under the NEW 3-segment structure, plus which year-column (after stripping
# None cells) holds that year's data.
OPERATIONAL_FY_SOURCES: dict[int, tuple[int, int]] = {
    2023: (2024, 1),  # FY24 40-F, prior-year column = FY23 restated
    2024: (2025, 1),  # FY25 40-F, prior-year column
    2025: (2025, 0),  # FY25 40-F, current-year column
}


def populate_segment_operational_detail(
    workbook_path: str | Path,
    *,
    segment_cache_dir: Path | None = None,
) -> int:
    """Stamp the per-segment operational-detail section into Model.

    Returns the number of value cells written (excluding labels).
    """
    workbook_path = Path(workbook_path)
    wb = load_workbook(workbook_path)
    ws = wb["Model"]

    # Parse the two filings that carry the 3-segment structure.
    parsed: dict[int, tuple[list[int], dict]] = {}
    for idx, src_fy in enumerate((2024, 2025)):
        if idx > 0:
            time.sleep(0.25)
        text = fetch_segment_report(src_fy, cache_dir=segment_cache_dir)
        parsed[src_fy] = parse_segment_html(text)

    # Section header.
    ws.cell(row=OPERATIONAL_SECTION_TITLE_ROW, column=2).value = (
        "SEGMENT OPERATIONAL DETAIL — NEW 3-SEGMENT STRUCTURE (FY23 restated, FY24, FY25)"
    )
    ws.cell(row=OPERATIONAL_SECTION_TITLE_ROW + 1, column=2).value = (
        "Per-segment financial decomposition tagged in TFI's 40-F Note "
        "'Segment Reporting (Details)'. Values in $M (R-files report $ "
        "thousands). FY23 is the restated comparative from the FY24 40-F; "
        "FY24-FY25 are from the FY25 40-F. Columns align with BT/BY/CD."
    )

    written = 0
    for i, seg_name in enumerate(OPERATIONAL_SEGMENTS):
        block_start = OPERATIONAL_FIRST_BLOCK_ROW + i * OPERATIONAL_BLOCK_STEP

        # Segment header (column B).
        ws.cell(row=block_start, column=2).value = (
            f"{seg_name} — Segment Disclosure"
        )

        for j, (template_label, rfile_label) in enumerate(OPERATIONAL_LINE_ITEMS):
            target_row = block_start + 1 + j
            ws.cell(row=target_row, column=2).value = template_label

            for fy, (src_fy, col_idx) in OPERATIONAL_FY_SOURCES.items():
                years_in_file, segs = parsed[src_fy]
                if seg_name not in segs:
                    continue
                line_vals = segs[seg_name].get(rfile_label)
                if not line_vals:
                    continue
                filtered = [v for v in line_vals if v is not None]
                if col_idx >= len(filtered):
                    continue
                v_m = filtered[col_idx] / 1_000.0
                ws.cell(row=target_row, column=fy_total_col(fy)).value = v_m
                written += 1

    wb.save(workbook_path)
    return written


# ---------------------------------------------------------------------------
# Workbook write
# ---------------------------------------------------------------------------

# Populated consolidated range. FY19 is included so the row 161-164 / 211
# y/y% formulas (e.g., =BE114/AZ114-1) have a populated prior-year cell to
# divide against — the alternative would be wrapping every consolidated y/y%
# formula in the source template with IFERROR.
FISCAL_YEARS = range(2019, 2026)


def populate(
    workbook_path: str | Path,
    *,
    years: Iterable[int] = FISCAL_YEARS,
    facts_cache: Path | None = None,
    segment_cache_dir: Path | None = None,
    skip_segments: bool = False,
) -> dict[tuple[int, int], float]:
    """Populate ``workbook_path`` in place with TFI's IFRS historicals.

    Returns a dict of ``{(year, row): value}`` actually written for the
    consolidated facts, so callers can audit coverage. Segment writes are
    reported separately via ``populate_segments``.
    """
    workbook_path = Path(workbook_path)
    facts = fetch_facts(cache_path=facts_cache)
    wb = load_workbook(workbook_path)
    ws = wb["Model"]

    written: dict[tuple[int, int], float] = {}
    for year in years:
        col = fy_total_col(year)
        for m in ALL_MAPPINGS:
            v = resolve_value(facts, m, year)
            if v is None:
                continue
            ws.cell(row=m.row, column=col).value = v
            written[(year, m.row)] = v

    wb.save(workbook_path)

    if not skip_segments:
        seg_written = populate_segments(
            workbook_path, segment_cache_dir=segment_cache_dir
        )
        populate.last_segment_writes = seg_written  # type: ignore[attr-defined]
    else:
        populate.last_segment_writes = {}  # type: ignore[attr-defined]

    populate.last_yoy_writes = add_yoy_formulas(workbook_path)  # type: ignore[attr-defined]

    if not skip_segments:
        populate.last_operational_writes = populate_segment_operational_detail(  # type: ignore[attr-defined]
            workbook_path, segment_cache_dir=segment_cache_dir,
        )
    else:
        populate.last_operational_writes = 0  # type: ignore[attr-defined]

    return written


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Populate TFI International historicals into a model template."
    )
    parser.add_argument(
        "workbook",
        type=Path,
        help="Path to the TFI model .xlsx (will be modified in place).",
    )
    parser.add_argument(
        "--facts-cache",
        type=Path,
        default=None,
        help="Optional path to cache the EDGAR Company Facts JSON.",
    )
    parser.add_argument(
        "--segment-cache",
        type=Path,
        default=None,
        help="Optional directory to cache per-year segment R-files (segment_YYYY.htm).",
    )
    parser.add_argument(
        "--skip-segments",
        action="store_true",
        help="Skip parsing 40-F segment R-files; populate consolidated IS/CF/BS only.",
    )
    args = parser.parse_args(argv)

    written = populate(
        args.workbook,
        facts_cache=args.facts_cache,
        segment_cache_dir=args.segment_cache,
        skip_segments=args.skip_segments,
    )
    print(f"Consolidated: {len(written)} cells across {len({y for y, _ in written})} fiscal years.")
    by_year: dict[int, int] = {}
    for (y, _), _ in written.items():
        by_year[y] = by_year.get(y, 0) + 1
    for y in sorted(by_year):
        print(f"  FY{y}: {by_year[y]} cells")
    seg_written = getattr(populate, "last_segment_writes", {})
    if seg_written:
        seg_years = {y for y, _, _ in seg_written}
        print(f"Segments:     {len(seg_written)} cells across {len(seg_years)} fiscal years.")
        seg_by_year: dict[int, int] = {}
        for (y, _, _), _ in seg_written.items():
            seg_by_year[y] = seg_by_year.get(y, 0) + 1
        for y in sorted(seg_by_year):
            print(f"  FY{y}: {seg_by_year[y]} cells")
    yoy_written = getattr(populate, "last_yoy_writes", 0)
    if yoy_written:
        print(f"Formula completions: {yoy_written} cells (y/y% + margins + cross-block FY24)")
    op_written = getattr(populate, "last_operational_writes", 0)
    if op_written:
        print(f"Operational detail:  {op_written} cells (3-seg FY23 restated -> FY25)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
